### ISSUE TITLE
Update STOFS-operational repo in OCS-modeling

### ISSUE THREAD

**Issue by gseroka** [noaa-ocs-modeling/STOFS-operational#2]
@yangz888 could you update this STOFS-operational repo https://github.com/noaa-ocs-modeling/STOFS-operational? It seems to have been included on Sep 27, 2022, so after our code handoff but before NCO made some final changes. Please feel free to reach out to @saeed-moghimi-noaa @pvelissariou1 @ps2epsi if you need help.

Thank you,
Greg

CC @ps2epsi @saeed-moghimi-noaa @pvelissariou1

**Comment by yangz888** [comment]
Hi Greg,

I've just completed updating the STOFS-3d-alt files with the NCO's OPS
copies (source: WCOSS2:/lfs/h1/ops/prod/packages/stofs.v1.1.1).

Please see the updated files and comments at
https://github.com/noaa-ocs-modeling/STOFS-operational).

Best,
Zizang

**Comment by gseroka** [comment]
Thank you @yangz888!! Did you initially commit STOFS-2D-Glo files as well, or was that Yuji @ps2epsi?

**Comment by saeed-moghimi-noaa** [comment]
Thanks @yangz888

**Comment by gseroka** [comment]
I think STOFS-2D-Glo needs to be updated still...

**Comment by yangz888** [comment]
Hi Greg,

Yuji took care of that.

Best,
Zizang

**Comment by gseroka** [comment]
thanks @yangz888. Yuji @ps2epsi, could you update the STOFS-2D-Glo components here with the operational version on WCOSS2?

**Comment by pvelissariou1** [comment]
All ocs modeling repos are backed up via the vlab gold copy.
Let's try to keep the repos up to date as much as possible.
Here is the list of the repos/branches being backed up:

-----------------------------------------------------------
[submodule "adcircpy"]
path = adcircpy
url = https://github.com/noaa-ocs-modeling/adcircpy.git
branch = main
[submodule "ATMESH"]
path = ATMESH
url = https://github.com/noaa-ocs-modeling/ATMESH.git
branch = master
[submodule "autoval"]
path = autoval
url = https://github.com/noaa-ocs-modeling/autoval.git
branch = master
[submodule "BARDATA"]
path = BARDATA
url = https://github.com/noaa-ocs-modeling/BARDATA.git
branch = main
[submodule "CoastalApp"]
path = CoastalApp
url = https://github.com/noaa-ocs-modeling/CoastalApp.git
branch = main
[submodule "coastal-act"]
path = coastal-act
url = https://github.com/noaa-ocs-modeling/coastal-act.git
branch = main
[submodule "CoupledModelDriver"]
path = CoupledModelDriver
url = https://github.com/noaa-ocs-modeling/CoupledModelDriver.git
branch = main
[submodule "csdllib"]
path = csdllib
url = https://github.com/noaa-ocs-modeling/csdllib.git
branch = master
[submodule "EnsemblePerturbation"]
path = EnsemblePerturbation
url = https://github.com/noaa-ocs-modeling/EnsemblePerturbation.git
branch = main
[submodule "NEMS"]
path = NEMS
url = https://github.com/noaa-ocs-modeling/NEMS.git
branch = develop
[submodule "nemspy"]
path = nemspy
url = https://github.com/noaa-ocs-modeling/nemspy.git
branch = main
[submodule "noaa-ocs-modeling.github.io"]
path = noaa-ocs-modeling.github.io
url = https://github.com/noaa-ocs-modeling/noaa-ocs-modeling.github.io.git
branch = main
[submodule "nwm_public_nuopc"]
path = nwm_public_nuopc
url = https://github.com/noaa-ocs-modeling/nwm_public_nuopc.git
branch = master
[submodule "PaHM"]
path = PaHM
url = https://github.com/noaa-ocs-modeling/PaHM.git
branch = main
[submodule "PyOFS"]
path = PyOFS
url = https://github.com/noaa-ocs-modeling/PyOFS.git
branch = master
[submodule "OCSMesh"]
path = OCSMesh
url = https://github.com/noaa-ocs-modeling/OCSMesh.git
branch = main
[submodule "seabed"]
path = seabed
url = https://github.com/noaa-ocs-modeling/seabed.git
branch = main
[submodule "thyme"]
path = thyme
url = https://github.com/noaa-ocs-modeling/thyme.git
branch = master
[submodule "TechMemoTemplate"]
path = TechMemoTemplate
url = https://github.com/noaa-ocs-modeling/TechMemoTemplate.git
branch = main
[submodule "WW3"]
path = WW3
url = https://github.com/noaa-ocs-modeling/WW3.git
branch = master
[submodule "WW3DATA"]
path = WW3DATA
url = https://github.com/noaa-ocs-modeling/WW3DATA.git
branch = master
[submodule "ondemand-storm-workflow"]
path = ondemand-storm-workflow
url = https://github.com/noaa-ocs-modeling/ondemand-storm-workflow.git
branch = main
[submodule "CoastalApp-testsuite"]
path = CoastalApp-testsuite
url = https://github.com/noaa-ocs-modeling/CoastalApp-testsuite.git
branch = main
[submodule "STOFS-operational"]
path = STOFS-operational
url = https://github.com/noaa-ocs-modeling/STOFS-operational.git
branch = main
[submodule "mesh_configurations"]
path = mesh_configurations
url = https://github.com/noaa-ocs-modeling/mesh_configurations.git
branch = main
[submodule "ufs-coastal"]
path = ufs-coastal
url = https://github.com/noaa-ocs-modeling/ufs-coastal.git
branch = develop
[submodule "VDatum-Spatially-Varying-Uncertainty"]
path = VDatum-Spatially-Varying-Uncertainty
url =
https://github.com/noaa-ocs-modeling/VDatum-Spatially-Varying-Uncertainty.git
branch = main
[submodule "csdlpy-1.5.1"]
path = csdlpy-1.5.1
url = https://github.com/noaa-ocs-modeling/csdlpy-1.5.1.git
branch = master

Takis

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Physical Scientist - Project Lead
cell: (205) 227-9141
email: ***@***.***

**Comment by ps2epsi** [comment]
Greg -
 I can not upload STOFS-2D-GLO components because of authorization issues.remote: Support for password authentication was removed on August 13, 2021.remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.fatal: Authentication failed for 'https://github.com/noaa-ocs-modeling/STOFS-operational.git/'
I can not commit or push any files since I've created a new account in 2021 (adding ***@***.***).
>ZizangIf you don't mind, can you add stofs-2d-glo componets to github?
Thanks,Yuji

-------------------------- 8621 Georgia Ave Apt 1517 Silver Spring MD, 20910 TEL: (301) 318-6513 MAILTO: ***@***.*** YUJI FUNAKOSHI -------------------------- 

    On Friday, March 17, 2023 at 12:57:03 PM EDT, Greg Seroka ***@***.***> wrote:  
 
 


thanks @yangz888. Yuji @ps2epsi, could you update the STOFS-2D-Glo components here with the operational version on WCOSS2?

**Comment by yangz888** [comment]
Hi Yuji,

*"ZizangIf you don't mind, can you add stofs-2d-glo componets to github?"*

I'll be very glad to do it. Will keep you updated on the progress. It may
take a short while - I'll need to scp the files to Frontera, scp to my PC,
and upload the files.

Best,
Zizang

**Comment by ps2epsi** [comment]
Zizang -
Thank you for your help.
Thanks,Yuji
-------------------------- 8621 Georgia Ave Apt 1517 Silver Spring MD, 20910 TEL: (301) 318-6513 MAILTO: ***@***.*** YUJI FUNAKOSHI -------------------------- 

    On Friday, March 17, 2023 at 02:10:32 PM EDT, yangz888 ***@***.***> wrote:  
 
 

Hi Yuji,

*"ZizangIf you don't mind, can you add stofs-2d-glo componets to github?"*

I'll be very glad to do it. Will keep you updated on the progress. It may
take a short while - I'll need to scp the files to Frontera, scp to my PC,
and upload the files.

Best,
Zizang

**Comment by yangz888** [comment]
Hi Yuji and all,

The files have been uploaded.
(1) Please see the package at
https://github.com/noaa-ocs-modeling/STOFS-operational.
(2) Note that the "fix/" folder can't be uploaded due to the "huge" file
sizes of fix/*. In fact, it was not uploaded it when we initiated the STOFS
repository. See a brief note in
https://github.com/noaa-ocs-modeling/STOFS-operational/blob/main/README.md.

Best,
Zizang

**Comment by saeed-moghimi-noaa** [comment]
Thanks a lot. -Saeed

**Comment by gseroka** [comment]
Thank you @yangz888!

**Comment by ps2epsi** [comment]
Zizang -
It looks good to me.Thank you for your help.
Thanks,Yuji
-------------------------- 8621 Georgia Ave Apt 1517 Silver Spring MD, 20910 TEL: (301) 318-6513 MAILTO: ***@***.*** YUJI FUNAKOSHI -------------------------- 

    On Friday, March 17, 2023 at 03:34:57 PM EDT, yangz888 ***@***.***> wrote:  
 
 

Hi Yuji and all,

The files have been uploaded.
(1) Please see the package at
https://github.com/noaa-ocs-modeling/STOFS-operational.
(2) Note that the "fix/" folder can't be uploaded due to the "huge" file
sizes of fix/*. In fact, it was not uploaded it when we initiated the STOFS
repository. See a brief note in
https://github.com/noaa-ocs-modeling/STOFS-operational/blob/main/README.md.

Best,
Zizang
